repos:
- repo: https://github.com/psf/black
  rev: "22.10.0"
  hooks:
    - id: black
- repo: https://github.com/PyCQA/isort
  rev: "5.12.0"
  hooks:
    - id: isort
- repo: https://github.com/PyCQA/flake8
  rev: "7.0.0"
  hooks:
    - id: flake8
# mypy is configured as a "local" repo so that it has access to the installed
# virtualenv. The alternative is to list all the necessary packages for
# type-checking as additional_dependencies, and without something like
# https://github.com/pre-commit/pre-commit/issues/730 this will lead to
# unwanted duplication.
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: python
      files: '\.pyi?$'
      # Passing filenames to mypy can do odd things. See
      # https://github.com/pre-commit/mirrors-mypy/issues/33.
      # mypy.ini determines the set of files that will actually be checked.
      pass_filenames: false
- repo: https://github.com/jazzband/pip-tools
  rev: 7.3.0
  hooks:
    - id: pip-compile
      name: pip-compile setup.cfg
      args:
        - --output-file=requirements.txt
        # --strip-extras makes the output usable as a constraint file
        - --strip-extras
        - setup.cfg
      language_version: python3.8
      files: '^(requirements\.txt|setup\.cfg)$'
    - id: pip-compile
      name: pip-compile test-requirements.in
      args:
        - --output-file=test-requirements.txt
        - --strip-extras
        - test-requirements.in
      language_version: python3.8
      files: '^((test-)?requirements\.(in|txt)|setup\.cfg)$'
