global:
  scrape_interval: 4s
  evaluation_interval: 4s
  external_labels:
    monitor: 'Sandbox'

scrape_configs:
  - job_name: 'katsdpcontroller'
    static_configs:
      - targets:
        - "127.0.0.1:5004"
