global:
  scrape_interval: 4s
  evaluation_interval: 4s
  external_labels:
    monitor: 'Sandbox'

scrape_configs:
  - job_name: 'katsdpcontroller'
    static_configs:
      - targets:
        - "127.0.0.1:5004"
  - job_name: 'product_controller'
    consul_sd_configs:
      - refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: product-controller
        action: keep
      - source_labels: [__meta_consul_service_metadata_subarray_product_id]
        target_label: subarray_product_id
      - source_labels: [__meta_consul_service_metadata_subarray_product_id]
        target_label: instance
